parameters:
  maith_common.bcucotizador.class: Maith\Common\AdminBundle\Services\BcuCotizadorService
  maith_common.admin.parameters.class: Maith\Common\AdminBundle\Services\MaithParametersService
  maith_common.admin.twig.avatar.class: Maith\Common\AdminBundle\Twig\mAvatarExtension
  maith_common.admin.listener.delete.class: Maith\Common\AdminBundle\Listener\DeleteListener
  maith_common.admin.staticfiles.manager.class: Maith\Common\AdminBundle\Services\StaticFilesService
  #maith_common.admin.galery.manager.class: Maith\Common\AdminBundle\Model\GalleryManager
  maith_common.cache.class: Doctrine\Common\Cache\FilesystemCache
  maith_common.email.service.class: Maith\Common\AdminBundle\Services\MaithEmailService
  maith_common.albums.service.class: Maith\Common\AdminBundle\Services\MaithAlbumService
  #    maith_common_admin.example.class: Maith\Common\AdminBundle\Example
  maith_common.email.service.multiplemailers: 1
  maith_common.email.service.maximunperhour: 999
  maith_common.email.mailers_names: [swiftmailer.mailer.first_mailer,swiftmailer.mailer.second_mailer,swiftmailer.mailer.third_mailer]

services:
  maith_common_admin.upload:
    class: Maith\Common\AdminBundle\Listener\RequestListener
    arguments: ["%maith_common_admin.upload_token%"]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 200 }

  maith_common_delete_listener:
    class: "%maith_common.admin.listener.delete.class%"
    tags:
      - { name: doctrine.event_listener, event: preRemove }

  maith_common.bcucotizador:
    class: "%maith_common.bcucotizador.class%"
    arguments: ["@doctrine.orm.entity_manager"]

  media_gallery_manager:
    class: "%maith_common.admin.staticfiles.manager.class%"
    arguments: ["@logger", "%kernel.project_dir%", "galleries"]

#  media_wyswyg_manager:
#    class: "%maith_common.admin.staticfiles.manager.class%"
#    arguments: ["@logger", "%kernel.root_dir%", "wyswyg"]

  media_album_service:
    class: "%maith_common.albums.service.class%"
    arguments: ["@doctrine.orm.entity_manager", "@logger"]

#  maith_common.parameters:
#    class: "%maith_common.admin.parameters.class%"
#    arguments: ["%kernel.root_dir%"]

  maith_common.email:
    class: "%maith_common.email.service.class%"
    arguments: ["@service_container", "@doctrine.orm.entity_manager", "@logger", "%maith_common.email.service.multiplemailers%", "%maith_common.email.service.maximunperhour%", "%maith_common.email.mailers_names%"]
    lazy: true

  Maith\Common\AdminBundle\Controller\AlbumsController:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['controller.service_arguments']

  Maith\Common\AdminBundle\Controller\AdminParametersController:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['controller.service_arguments']

  Maith\Common\AdminBundle\Controller\MediaWyswygController:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['controller.service_arguments']

  Maith\Common\AdminBundle\Services\AlbumCacheService:
    arguments:
      $cache: '@cache.app'

  maith_common.cache:
    alias: Maith\Common\AdminBundle\Services\AlbumCacheService

  maith_common_admin.twig.maith_m_avatar:
    class: "%maith_common.admin.twig.avatar.class%"
    arguments:
      - "@doctrine.orm.entity_manager"
      - "%kernel.project_dir%"
      - "@maith_common.cache"
    tags:
      - { name: twig.extension }

  Maith\Common\AdminBundle\Services\StaticFilesService:
    arguments:
      $logger: '@logger'
      $documentRoot: '%kernel.root_dir%'
      $filesRoot: 'wyswyg'

  Maith\Common\AdminBundle\Services\MaithParametersService:
    arguments:
      $projectRootDirectory: '%kernel.project_dir%'

  Maith\Common\AdminBundle\Repository\mAlbumRepository:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['doctrine.repository_service']

  Maith\Common\AdminBundle\Controller\CacheCommandController:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['controller.service_arguments']

  Maith\Common\AdminBundle\Controller\PublicStaticController:
    autowire: true # or define your controller constructor and configure its arguments explicitly
    tags: ['controller.service_arguments']

  Maith\Common\AdminBundle\Services\StaticFileUrlGeneratorService:
    arguments:
      $router: '@router'
